# Generated by Django 5.2.3 on 2025-07-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_package_destination_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryhistory',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Delivery Histories'},
        ),
    ]
